---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: udaconnect-location-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udaconnect-location-consumer
  template:
    metadata:
      labels:
        app: udaconnect-location-consumer
    spec:
      containers:
      - image: deviesadocker/udaconnect-location-consumer:latest
        name: udaconnect-location-consumer
        imagePullPolicy: Always
        env:
        - name: FLASK_KAFKA_SERVER
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: FLASK_KAFKA_SERVER
        - name: FLASK_KAFKA_TOPIC
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: FLASK_KAFKA_TOPIC
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
      restartPolicy: Always
